export declare const Wrapper: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const Header: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const HeaderTitle: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const HeaderSubtitle: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const Footer: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const Title: import("styled-components").StyledComponent<"p", any, any, never>;
export declare const Subtitle: import("styled-components").StyledComponent<"p", any, {}, never>;
export declare const SubtitleValue: import("styled-components").StyledComponent<"p", any, {}, never>;
export declare const FavoriteIcon: import("styled-components").StyledComponent<"img", any, {}, never>;
