import { ImageProps } from '../../molecules/Menu/types';
export declare const Container: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const InnerContainer: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const DialogHeaderContainer: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const DialogHeader: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const DialogTitle: import("styled-components").StyledComponent<"p", any, {}, never>;
export declare const CloseButton: import("styled-components").StyledComponent<"button", any, {}, never>;
export declare const FavoriteIcon: import("styled-components").StyledComponent<"img", any, {}, never>;
export declare const TokenPairWrapper: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const IconWrapper: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const Icon: import("styled-components").StyledComponent<"img", any, ImageProps, never>;
export declare const PoolText: import("styled-components").StyledComponent<"p", any, {}, never>;
export declare const PoolKeyPairContainer: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const PoolKey: import("styled-components").StyledComponent<"p", any, {}, never>;
export declare const PoolValue: import("styled-components").StyledComponent<"p", any, {}, never>;
